In [1]:
import pickle
from pathlib import Path
import pandas as pd 
import os
import sys

In [2]:
import data_set_generate_helper_functions as ghf

In [3]:
sys.executable

'/anaconda3/bin/python3'

# Path to import the data and where to save it

In [4]:
path = "/Volumes/GilInVivoPaper.large/2.Photometry_in_str/1.lateral_medial_6_analysis_1"

# Update depending on analysis:

In [5]:
seq_str = '0a1a2a3j4abcd5a6a7a'
HowManyBack=1

# Folder to save the data:

In [6]:
#folderName="right_dual_color_photo_full_data_after_QC" #folder where the plot data_set will be saved 
folderName="left_dual_color_photo_full_data_set_after_inspection" #folder where the plot data_set will be saved

In [7]:
path_to_save = path+"/"+folderName+"/"+seq_str
path_to_save

'/Volumes/GilInVivoPaper.large/2.Photometry_in_str/1.lateral_medial_6_analysis_1/left_dual_color_photo_full_data_set_after_inspection/0a1a2a3j4abcd5a6a7a'

# import the data table:

In [8]:
#name of xlsx file that has the sessions we want to run: 
#MasterSheetName= '3.lateral_medial_6_lateral_channels_final'
MasterSheetName= '4.lateral_medial_6_medial_channels_final'

In [9]:
Mouse_Date_FileName = pd.read_excel(path+'/'+MasterSheetName+'.xlsx') #mdf is mouse data file

In [10]:
Mouse_Date_FileName

   mouse    date    file name
0   T163  181127  T163-144959
1   T163  181207  T163-123432
2   T163  181128  T163-115220
3   T163  181204  T163-114628
4   T163  181206  T163-112720
5   T163  181210  T163-102536
6   T163  181213  T163-094646
7   T164  181127  T164-153101
8   T164  181203  T164-122950
9   T164  181128  T164-122054
10  T169  190211  T169-145303
11  T169  190212  T169-145045
12  T169  190226  T169-142505
13  T169  190222  T169-134725
14  T169  190225  T169-145248
15  T169  190125  T169-142626
16  T169  190214  T169-143937
17  T169  190220  T169-141850
18  T169  190219  T169-140515
19  T169  190201  T169-141602
20  T169  190228  T169-142051
21  T169  190131  T169-143728
22  T170  190131  T170-150622
23  T170  190125  T170-150000
24  T170  190201  T170-145715
25  T170  190220  T170-150418
26  T171  190219  T171-150804
27  T171  190128  T171-144901
28  T171  190301  T171-144116
29  T171  190123  T171-165937
30  T171  190221  T171-152107
31  T171  190226  T171-145215
32  T171  190213  T171-151952
33  T171  190122  T171-165215
34  T171  190214  T171-155052
35  T171  190220  T171-153511
36  T171  190222  T171-145829
37  T171  190208  T171-170021
38  T171  190125  T171-153230
39  T171  190215  T171-152142
40  T171  190212  T171-164950
41  T171  190211  T171-143016
42  T171  190131  T171-153700
43  T171  190130  T171-145252
44  T186  190321  T186-153107
45  T186  190325  T186-150810
46  T186  190322  T186-164847
47  T186  190401  T186-142719
48  T186  190328  T186-144534
49  T186  190327  T186-150703
50  T186  190402  T186-140234
51  T186  190405  T186-135725
52  T187  190322  T187-172139
53  T187  190325  T187-153540
54  T187  190401  T187-150132
55  T187  190403  T187-143148
56  T202  190522  T202-141516
57  T202  190529  T202-160644
58  T202  190516  T202-165613

In [11]:
#Mouse_Date_FileName = Mouse_Date_FileName.iloc[0:45,:]

In [12]:
#Mouse_Date_FileName

# Import the full data structure for each session:

In [13]:
# def generate_date_(Date):
#     return('20'+str(Date)[:2]+'_'+str(Date)[2:4]+'_'+str(Date)[4:6])

# def generate_name_and_date(Date,Mouse):
#     return ('20'+str(Date)[:2]+'_'+str(Date)[2:4]+'_'+str(Date)[4:6]+'__'+Mouse)

In [14]:
%%time
data_trial_data_set = ghf.extract_data_object_data_trial(Mouse_Date_FileName,path,HowManyBack)

session number 1 was imported (out of 59)
session number 2 was imported (out of 59)
session number 3 was imported (out of 59)
session number 4 was imported (out of 59)
session number 5 was imported (out of 59)
session number 6 was imported (out of 59)
session number 7 was imported (out of 59)
session number 8 was imported (out of 59)
session number 9 was imported (out of 59)
session number 10 was imported (out of 59)
session number 11 was imported (out of 59)
session number 12 was imported (out of 59)
session number 13 was imported (out of 59)
session number 14 was imported (out of 59)
session number 15 was imported (out of 59)
session number 16 was imported (out of 59)
session number 17 was imported (out of 59)
session number 18 was imported (out of 59)
session number 19 was imported (out of 59)
session number 20 was imported (out of 59)
session number 21 was imported (out of 59)
session number 22 was imported (out of 59)
session number 23 was imported (out of 59)
session number 24 was imported (out of 59)
session number 25 was imported (out of 59)
session number 26 was imported (out of 59)
session number 27 was imported (out of 59)
session number 28 was imported (out of 59)
session number 29 was imported (out of 59)
session number 30 was imported (out of 59)
session number 31 was imported (out of 59)
session number 32 was imported (out of 59)
session number 33 was imported (out of 59)
session number 34 was imported (out of 59)
session number 35 was imported (out of 59)
session number 36 was imported (out of 59)
session number 37 was imported (out of 59)
session number 38 was imported (out of 59)
session number 39 was imported (out of 59)
session number 40 was imported (out of 59)
session number 41 was imported (out of 59)
session number 42 was imported (out of 59)
session number 43 was imported (out of 59)
session number 44 was imported (out of 59)
session number 45 was imported (out of 59)
session number 46 was imported (out of 59)
session number 47 was imported (out of 59)
session number 48 was imported (out of 59)
session number 49 was imported (out of 59)
session number 50 was imported (out of 59)
session number 51 was imported (out of 59)
session number 52 was imported (out of 59)
session number 53 was imported (out of 59)
session number 54 was imported (out of 59)
session number 55 was imported (out of 59)
session number 56 was imported (out of 59)
session number 57 was imported (out of 59)
session number 58 was imported (out of 59)
session number 59 was imported (out of 59)
CPU times: user 93.5 ms, sys: 33.7 ms, total: 127 ms
Wall time: 433 ms

In [15]:
data_set = data_trial_data_set.copy()

In [16]:
list(data_set[0].keys())

['iSpout',
 'iBlock',
 'iTrial',
 'iTrial_post',
 'iReward',
 'iError',
 'I_listeningRig',
 'sCue',
 'T_Cue_Audio',
 'T_Cue_LED',
 'sTrial_start',
 'sTrial_end',
 'sSelection',
 'tSelection',
 'I_anySelect_L',
 'I_anySelect_R',
 'I_giveReward',
 'T_Reward',
 'L_power_l1',
 'L_power_l2',
 'L_T_l1',
 'L_T_l2',
 'T_ENL',
 'n_ENL',
 'L_ENL_event_n_l1',
 'L_ENL_event_n_l2',
 'L_ENL_trig_n_l1',
 'L_ENL_trig_n_l2',
 'L_ENL_event_I_l1',
 'L_ENL_event_I_l2',
 'L_ENL_trig_I_l1',
 'L_ENL_trig_I_l2',
 'n_Cue',
 'L_Cue_event_n_l1',
 'L_Cue_event_n_l2',
 'L_Cue_trig_n_l1',
 'L_Cue_trig_n_l2',
 'L_Cue_event_I_l1',
 'L_Cue_event_I_l2',
 'L_Cue_trig_I_l1',
 'L_Cue_trig_I_l2',
 'L_Sel_event_n_l1',
 'L_Sel_event_n_l2',
 'L_Sel_trig_n_l1',
 'L_Sel_trig_n_l2',
 'L_Sel_event_I_l1',
 'L_Sel_event_I_l2',
 'L_Sel_trig_I_l1',
 'L_Sel_trig_I_l2',
 'L_Rew_event_I_l1',
 'L_Rew_event_I_l2',
 'L_Rew_trig_I_l1',
 'L_Rew_trig_I_l2',
 'L_Wro_event_I_l1',
 'L_Wro_event_I_l2',
 'L_Wro_trig_I_l1',
 'L_Wro_trig_I_l2',
 'sCue2',
 'T_Cue2_Audio',
 'T_Cue2_LED',
 'T_ENL2',
 'n_ENL2',
 'L_ENL2_event_n_l1',
 'L_ENL2_event_n_l2',
 'L_ENL2_trig_n_l1',
 'L_ENL2_trig_n_l2',
 'L_ENL2_event_I_l1',
 'L_ENL2_event_I_l2',
 'L_ENL2_trig_I_l1',
 'L_ENL2_trig_I_l2',
 'n_Cue2',
 'L_Cue2_event_n_l1',
 'L_Cue2_event_n_l2',
 'L_Cue2_trig_n_l1',
 'L_Cue2_trig_n_l2',
 'L_Cue2_event_I_l1',
 'L_Cue2_event_I_l2',
 'L_Cue2_trig_I_l1',
 'L_Cue2_trig_I_l2',
 'DAB_I_HighProbSel',
 'DAB_I_flipLR_event',
 'DAB_I_flipLR',
 'DAB_iSelect_L',
 'DAB_iSelect_R',
 'DAB_iSelect_HighProb',
 'DAB_iSelect_LowProb',
 'Unnamed: 87',
 'Unnamed: 88',
 'Unnamed: 89',
 'Unnamed: 90',
 'Unnamed: 91',
 'Unnamed: 92',
 'Unnamed: 93',
 'Date',
 'Mouse',
 'direction',
 '-1_r',
 'SamePastDirection',
 '-1_d']

In [17]:
if not os.path.exists(path_to_save):
    os.makedirs(path_to_save)

In [18]:
%%time
root = Path(path_to_save)
d = "data_object_data_trial"+"_"+seq_str+'.pickle'
my_path = root / d

CPU times: user 53 µs, sys: 1e+03 ns, total: 54 µs
Wall time: 58.9 µs

In [19]:
my_file = open(my_path, 'wb')
my_file = pickle.dump((data_set),my_file)